Item Model and Service
sinfo/deck2 pull request #239
Opened 2021-07-17 16:24 UTC by Sofia-Morgado

Item Model and Service

Notas: não tenho a certeza se a função uploadItemImage se faz assim

2021-07-17 21:29 UTC, Dpac99 requested changes
Some methods have wrong name, may be a bit confusing

2021-07-17 21:29 UTC, Dpac99 commented on frontend/lib/services/itemService.dart
> +  Future<Item?> getBilling(String id) async {
Forgot to change method name :grin:

2021-07-17 22:58 UTC, Sofia-Morgado commented on frontend/lib/services/itemService.dart
> +  Future<Item?> getBilling(String id) async {
Thank you, fixed it.

2021-07-19 17:56 UTC, Dpac99 approved these changes

2021-07-19 17:57 UTC, merged